name="foil-test"
version="0.1"

[clone.UMA]
source="uma-oov3"
target="foil@uma-mock"
options.defaultCurrency = "<%= BondCurrency.Token.address %>"
options.minimumBond = "0"

[clone.Uniswap]
source="uniswap"
target="foil@uniswap"

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"
var.symbol="wstETH"

[clone.BondCurrency]
source="mintable-token@permissionless-mint"
target="foil@test-bond-currency"
var.symbol="USDC"
var.decimals = "6"

[deploy.ReentrancyGuard]
artifact = "ReentrancyGuard"

[deploy.EpochConfigurationModule]
artifact="EpochConfigurationModule"
libraries.ReentrancyGuard="<%= contracts.ReentrancyGuard.address %>"

[deploy.EpochLiquidityModule]
artifact="EpochLiquidityModule"

[deploy.EpochUMASettlementModule]
artifact="EpochUMASettlementModule"

[deploy.EpochTradeModule]
artifact="EpochTradeModule"

[deploy.EpochNftModule]
artifact="EpochNftModule"

[deploy.EpochViewsModule]
artifact="EpochViewsModule"

[deploy.EpochERC165Module]
artifact="EpochERC165Module"

[router.Foil]
contracts=[
  "EpochConfigurationModule",
  "EpochLiquidityModule",
  "EpochUMASettlementModule",
  "EpochTradeModule",
  "EpochNftModule",
  "EpochViewsModule",
  "EpochERC165Module",
]
